---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: 10.0.1.97:5000/jenkins-demo:1
        imagePullPolicy: Always
        name: web

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  ports:
  - nodePort: 32313
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
